package khansapos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.Color;
import java.awt.FontMetrics;
import java.awt.Graphics;
import javax.swing.JDesktopPane;

public class Beranda extends javax.swing.JFrame {

    public Beranda() {
        initComponents();
        Icon();
        setUser();   
        setWaktu();
        setJam(); 
 
   }
        


    private void Icon(){       
        ImageIcon icon = new ImageIcon("image/shopping-bags64.png");
        setIconImage(icon.getImage());        
    }
    
    private void setUser(){      
            String userId = Utility_Session.getUserId();
            String userName=Utility_Session.getUserName();
            String userLevel=Utility_Session.getUserLevel();          

            lblUser.setText(userLevel + ":  " +userName);
                 
    }
       
   private void setWaktu() {
            java.util.Date tglsekarang = new java.util.Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
            String tanggal = sdf.format(tglsekarang);
            SimpleDateFormat fTahun = new SimpleDateFormat(" yyyy", Locale.getDefault());
            int copyrightSymbolCodePoint = 169 ;
            String s = Character.toString( copyrightSymbolCodePoint ) ;
            String tahun=s +" Copy right " + fTahun.format(tglsekarang) + "  Rohmadi Cahyono";
             lblTanggal.setText(tanggal);
             lblCopyright.setText(tahun);
    }
  
    private void setJam(){
        ActionListener taskPerformer = (ActionEvent evt) -> {            
                String nol_jam = "", nol_menit = "";
                Calendar calendar = Calendar.getInstance();            
                int nilai_jam = calendar.get(Calendar.HOUR_OF_DAY);
                int nilai_menit = calendar.get(Calendar.MINUTE);
                // int nilai_detik = calendar.get(Calendar.SECOND);
                if(nilai_jam <= 9) nol_jam= "0";
                if(nilai_menit <= 9) nol_menit= "0";
                // if(nilai_detik <= 9) nol_detik= "0";
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                //String detik = nol_detik + Integer.toString(nilai_detik);
                lblJam.setText(jam+":"+menit);
                // lblJam.setText(jam+":"+menit+":"+detik+"");
        };
        new Timer(1000, taskPerformer).start();
    }  
        
    private void getSizeJDesktopPane(){
        Utility_Session.setPanelW(panelUtama1.getWidth());
        Utility_Session.setPanelH(panelUtama1.getHeight());   
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        Penjualan = new javax.swing.JMenuItem();
        pjBayar = new javax.swing.JMenuItem();
        pjRetur = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Pembelian = new javax.swing.JMenuItem();
        pbBayar = new javax.swing.JMenuItem();
        pbRetur = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        lapPembelian = new javax.swing.JMenuItem();
        lapPenjualan = new javax.swing.JMenuItem();
        lapLaba = new javax.swing.JMenuItem();
        lapGrafik = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        StokBarang = new javax.swing.JMenuItem();
        StokOpnam = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        Barang = new javax.swing.JMenu();
        mBarang = new javax.swing.JMenuItem();
        mBarangSatuan = new javax.swing.JMenuItem();
        mBarangKategori = new javax.swing.JMenuItem();
        mSuplier = new javax.swing.JMenuItem();
        mMember = new javax.swing.JMenuItem();
        mUser = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        logOut = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        panelSidebar = new javax.swing.JPanel();
        btnClose = new khansapos.Utility_ButtonMetro();
        btnClose7 = new khansapos.Utility_ButtonMetro();
        btnClose6 = new khansapos.Utility_ButtonMetro();
        btnClose5 = new khansapos.Utility_ButtonMetro();
        btnClose4 = new khansapos.Utility_ButtonMetro();
        btnClose10 = new khansapos.Utility_ButtonMetro();
        btnClose11 = new khansapos.Utility_ButtonMetro();
        btnClose8 = new khansapos.Utility_ButtonMetro();
        shortcutLogout = new khansapos.Utility_ButtonMetro();
        panelHeader = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        btnExit = new khansapos.Utility_ButtonMetro();
        btnExit1 = new khansapos.Utility_ButtonMetro();
        panelUtama1 =  new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(new Color(248,251,251));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        lblCopyright = new javax.swing.JLabel();

        popUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Penjualan.setBackground(new java.awt.Color(0, 0, 0));
        Penjualan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penjualan.setText("Penjualan");
        popUp.add(Penjualan);

        pjBayar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pjBayar.setText("Penjualan Bayar");
        popUp.add(pjBayar);

        pjRetur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pjRetur.setText("Penjualan Retur");
        popUp.add(pjRetur);
        popUp.add(jSeparator1);

        Pembelian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pembelian.setText("Pembelian");
        popUp.add(Pembelian);

        pbBayar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pbBayar.setText("Pembelian Bayar");
        popUp.add(pbBayar);

        pbRetur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pbRetur.setText("Pembelian Retur");
        popUp.add(pbRetur);
        popUp.add(jSeparator2);

        lapPembelian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lapPembelian.setText("Laporan Pembelian");
        popUp.add(lapPembelian);

        lapPenjualan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lapPenjualan.setText("Laporan Penjualan");
        popUp.add(lapPenjualan);

        lapLaba.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lapLaba.setText("Laporan Laba");
        popUp.add(lapLaba);

        lapGrafik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lapGrafik.setText("Laporan Grafik");
        popUp.add(lapGrafik);
        popUp.add(jSeparator3);

        StokBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StokBarang.setText("Stok Barang");
        popUp.add(StokBarang);

        StokOpnam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StokOpnam.setText("Stok Opname");
        popUp.add(StokOpnam);
        popUp.add(jSeparator5);

        Barang.setText("Barang");
        Barang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mBarang.setText("Master Barang");
        mBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBarangActionPerformed(evt);
            }
        });
        Barang.add(mBarang);

        mBarangSatuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mBarangSatuan.setText("Satuan Barang");
        mBarangSatuan.setToolTipText("");
        mBarangSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBarangSatuanActionPerformed(evt);
            }
        });
        Barang.add(mBarangSatuan);

        mBarangKategori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mBarangKategori.setText("Kategori Barang");
        mBarangKategori.setToolTipText("");
        mBarangKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBarangKategoriActionPerformed(evt);
            }
        });
        Barang.add(mBarangKategori);

        popUp.add(Barang);

        mSuplier.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mSuplier.setText("Master Suplier");
        mSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSuplierActionPerformed(evt);
            }
        });
        popUp.add(mSuplier);

        mMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMember.setText("Master Member");
        mMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMemberActionPerformed(evt);
            }
        });
        popUp.add(mMember);

        mUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mUser.setText("Master User");
        mUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUserActionPerformed(evt);
            }
        });
        popUp.add(mUser);
        popUp.add(jSeparator4);

        logOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        popUp.add(logOut);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\logoKhansa1.png")); // NOI18N
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 50));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        panelSidebar.setBackground(new java.awt.Color(0, 123, 255));
        panelSidebar.setPreferredSize(new java.awt.Dimension(120, 718));

        btnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        btnClose.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\006-checkout.png")); // NOI18N
        btnClose.setToolTipText("PENJUALAN");
        btnClose.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnClose.setMouseHover(new java.awt.Color(26, 149, 255));
        btnClose.setMousePress(new java.awt.Color(51, 174, 255));
        btnClose.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnClose7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        btnClose7.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\006-notes.png")); // NOI18N
        btnClose7.setToolTipText("PEMBAYARAN PENJUALAN");
        btnClose7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnClose7.setMouseHover(new java.awt.Color(26, 149, 255));
        btnClose7.setMousePress(new java.awt.Color(51, 174, 255));
        btnClose7.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnClose7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose7ActionPerformed(evt);
            }
        });

        btnClose6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        btnClose6.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\009-delivery.png")); // NOI18N
        btnClose6.setToolTipText("PEMBELIAN");
        btnClose6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnClose6.setMouseHover(new java.awt.Color(26, 149, 255));
        btnClose6.setMousePress(new java.awt.Color(51, 174, 255));
        btnClose6.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnClose6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose6ActionPerformed(evt);
            }
        });

        btnClose5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        btnClose5.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\019-loan.png")); // NOI18N
        btnClose5.setToolTipText("PEMBAYARAN PEMBELIAN");
        btnClose5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnClose5.setMouseHover(new java.awt.Color(26, 149, 255));
        btnClose5.setMousePress(new java.awt.Color(51, 174, 255));
        btnClose5.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnClose5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose5ActionPerformed(evt);
            }
        });

        btnClose4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        btnClose4.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\027-list.png")); // NOI18N
        btnClose4.setToolTipText("LAPORAN PEMBELIAN");
        btnClose4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnClose4.setMouseHover(new java.awt.Color(26, 149, 255));
        btnClose4.setMousePress(new java.awt.Color(51, 174, 255));
        btnClose4.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnClose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose4ActionPerformed(evt);
            }
        });

        btnClose10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        btnClose10.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\026-file.png")); // NOI18N
        btnClose10.setToolTipText("LAPORAN PENJUALAN");
        btnClose10.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnClose10.setMouseHover(new java.awt.Color(26, 149, 255));
        btnClose10.setMousePress(new java.awt.Color(51, 174, 255));
        btnClose10.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnClose10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose10ActionPerformed(evt);
            }
        });

        btnClose11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        btnClose11.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\009-time-is-money.png")); // NOI18N
        btnClose11.setToolTipText("LAPORAN LABA KOTOR");
        btnClose11.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnClose11.setMouseHover(new java.awt.Color(26, 149, 255));
        btnClose11.setMousePress(new java.awt.Color(51, 174, 255));
        btnClose11.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnClose11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose11ActionPerformed(evt);
            }
        });

        btnClose8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        btnClose8.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\011-graph.png")); // NOI18N
        btnClose8.setToolTipText("GRAFIK PENJUALAN");
        btnClose8.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnClose8.setMouseHover(new java.awt.Color(26, 149, 255));
        btnClose8.setMousePress(new java.awt.Color(51, 174, 255));
        btnClose8.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnClose8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose8ActionPerformed(evt);
            }
        });

        shortcutLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 174, 255)));
        shortcutLogout.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\lock-landscape-48.png")); // NOI18N
        shortcutLogout.setToolTipText("KUNCI APLIKASI");
        shortcutLogout.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        shortcutLogout.setMouseHover(new java.awt.Color(26, 149, 255));
        shortcutLogout.setMousePress(new java.awt.Color(51, 174, 255));
        shortcutLogout.setWarnaBackground(new java.awt.Color(0, 123, 255));
        shortcutLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortcutLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shortcutLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(shortcutLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(panelSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 120, -1));

        panelHeader.setBackground(new java.awt.Color(0, 0, 0));
        panelHeader.setPreferredSize(new java.awt.Dimension(1366, 50));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTanggal.setBackground(new java.awt.Color(0, 0, 0));
        lblTanggal.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTanggal.setText("23 September 2021");
        lblTanggal.setOpaque(true);
        panelHeader.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 198, 50));

        lblUser.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("Kasir: Cahyono");
        panelHeader.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 214, 50));

        lblJam.setBackground(new java.awt.Color(0, 0, 0));
        lblJam.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblJam.setForeground(new java.awt.Color(204, 204, 0));
        lblJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJam.setText("12:34");
        lblJam.setOpaque(true);
        panelHeader.add(lblJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 67, 50));

        btnExit.setMnemonic('x');
        btnExit.setText("Exit");
        btnExit.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnExit.setPreferredSize(new java.awt.Dimension(80, 50));
        btnExit.setWarnaBackground(new java.awt.Color(34, 67, 67));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelHeader.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 0, 80, 50));

        btnExit1.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\MenuIcon32.png")); // NOI18N
        btnExit1.setMnemonic('m');
        btnExit1.setText("Menu");
        btnExit1.setToolTipText(null);
        btnExit1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnExit1.setMouseHover(new java.awt.Color(60, 93, 93));
        btnExit1.setMousePress(new java.awt.Color(85, 118, 118));
        btnExit1.setName(""); // NOI18N
        btnExit1.setPreferredSize(new java.awt.Dimension(105, 50));
        btnExit1.setWarnaBackground(new java.awt.Color(34, 67, 67));
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        panelHeader.add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 110, 50));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelUtama1.setBackground(new java.awt.Color(248, 251, 251));
        panelUtama1.setMinimumSize(new java.awt.Dimension(1246, 698));

        javax.swing.GroupLayout panelUtama1Layout = new javax.swing.GroupLayout(panelUtama1);
        panelUtama1.setLayout(panelUtama1Layout);
        panelUtama1Layout.setHorizontalGroup(
            panelUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1246, Short.MAX_VALUE)
        );
        panelUtama1Layout.setVerticalGroup(
            panelUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        getContentPane().add(panelUtama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 1246, 698));

        lblCopyright.setBackground(new java.awt.Color(153, 153, 153));
        lblCopyright.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCopyright.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText(" Copy Right  2021  Rohmadi Cahyono");
        lblCopyright.setMaximumSize(new java.awt.Dimension(1246, 20));
        lblCopyright.setMinimumSize(new java.awt.Dimension(1246, 20));
        lblCopyright.setOpaque(true);
        lblCopyright.setPreferredSize(new java.awt.Dimension(1246, 20));
        getContentPane().add(lblCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 750, -1, -1));

        setBounds(0, 0, 1367, 764);
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {                                     
        popUp.show(this, 155, 55);
    }  
    
    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        Logout();
    }//GEN-LAST:event_logOutActionPerformed

    private void mUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUserActionPerformed
        UserFormShow();
    }//GEN-LAST:event_mUserActionPerformed

    private void mMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMemberActionPerformed
        MemberFormShow();
    }//GEN-LAST:event_mMemberActionPerformed

    private void mSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSuplierActionPerformed
        SuplierFormShow();
    }//GEN-LAST:event_mSuplierActionPerformed

    private void mBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBarangActionPerformed
        ItemFormShow();
    }//GEN-LAST:event_mBarangActionPerformed

    private void mBarangSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBarangSatuanActionPerformed
        ItemUnitShow();
    }//GEN-LAST:event_mBarangSatuanActionPerformed

    private void mBarangKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBarangKategoriActionPerformed
        ItemCategoryShow();
    }//GEN-LAST:event_mBarangKategoriActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Keluar();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        popUp.show(this, 155, 55); 
        getSizeJDesktopPane();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose4ActionPerformed

    private void btnClose5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose5ActionPerformed

    private void btnClose6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose6ActionPerformed

    private void btnClose7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose7ActionPerformed

    private void btnClose8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose8ActionPerformed

    private void shortcutLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortcutLogoutActionPerformed
        Logout();
    }//GEN-LAST:event_shortcutLogoutActionPerformed

    private void btnClose10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose10ActionPerformed

    private void btnClose11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose11ActionPerformed
  
      
    private void UserFormShow(){
        RemovePanel();
        UserForm Uf= new UserForm();
        panelUtama1.add(Uf);
        Uf.setVisible(true);           
    }
    
    private void MemberFormShow(){
        RemovePanel();
        MemberForm Mf = new MemberForm();
        panelUtama1.add(Mf);
        Mf.setVisible(true);
    }
    
    private void SuplierFormShow(){
        RemovePanel();
        SuplierForm Sf = new SuplierForm();
        panelUtama1.add(Sf);
        Sf.setVisible(true);
    }
    
    private void ItemFormShow(){
        RemovePanel();
        ItemForm If = new ItemForm();
        panelUtama1.add(If);
        If.setVisible(true);
    }
    
    private void ItemUnitShow(){
        RemovePanel();
        ItemUnit iu = new ItemUnit();
        panelUtama1.add(iu);
        iu.setVisible(true);
    }
      
    private void ItemCategoryShow(){
        RemovePanel();
        ItemCategory ic = new ItemCategory();
        panelUtama1.add(ic);
        ic.setVisible(true);
    }
    
    private void popUpMenu(){
           
    }
    
    public void RemovePanel(){
        panelUtama1.removeAll();
        panelUtama1.updateUI();      
    }
    
    private void Logout(){
          new LoginForm().setVisible(true);
         dispose();  
    }
    private void Keluar(){
        System.exit(0);
    }
    
    
    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {            
            new Beranda().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Barang;
    private javax.swing.JMenuItem Pembelian;
    private javax.swing.JMenuItem Penjualan;
    private javax.swing.JMenuItem StokBarang;
    private javax.swing.JMenuItem StokOpnam;
    private khansapos.Utility_ButtonMetro btnClose;
    private khansapos.Utility_ButtonMetro btnClose10;
    private khansapos.Utility_ButtonMetro btnClose11;
    private khansapos.Utility_ButtonMetro btnClose4;
    private khansapos.Utility_ButtonMetro btnClose5;
    private khansapos.Utility_ButtonMetro btnClose6;
    private khansapos.Utility_ButtonMetro btnClose7;
    private khansapos.Utility_ButtonMetro btnClose8;
    private khansapos.Utility_ButtonMetro btnExit;
    private khansapos.Utility_ButtonMetro btnExit1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem lapGrafik;
    private javax.swing.JMenuItem lapLaba;
    private javax.swing.JMenuItem lapPembelian;
    private javax.swing.JMenuItem lapPenjualan;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem mBarang;
    private javax.swing.JMenuItem mBarangKategori;
    private javax.swing.JMenuItem mBarangSatuan;
    private javax.swing.JMenuItem mMember;
    private javax.swing.JMenuItem mSuplier;
    private javax.swing.JMenuItem mUser;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JDesktopPane panelUtama1;
    private javax.swing.JMenuItem pbBayar;
    private javax.swing.JMenuItem pbRetur;
    private javax.swing.JMenuItem pjBayar;
    private javax.swing.JMenuItem pjRetur;
    private javax.swing.JPopupMenu popUp;
    private khansapos.Utility_ButtonMetro shortcutLogout;
    // End of variables declaration//GEN-END:variables
}
