package khansapos;

import java.awt.*; 
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.crypto.Cipher;  
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

        

public class Login extends javax.swing.JFrame {  
    public static String sessionId, sessionName, sessionLevel;
    static Cipher cipher;  
    private int count;
   
    public Login() {
        initComponents(); 
        setIcon();
        cekDatabase();
        SwingUtilities.invokeLater(() -> { txtUserName.requestFocusInWindow(); });
        super.setBackground(new Color(0, 0, 0, 0));        
    }
    

    
    private void setIcon(){
        ImageIcon icon = new ImageIcon("image/keys.png");
        setIconImage(icon.getImage());    
        
    }
    
    private void cekDatabase(){
        try{
            java.sql.Connection con =  new UDbConnection().koneksi();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs=st.executeQuery("SELECT COUNT(*) AS rowcount FROM users");
                rs.next();
                 count = rs.getInt("rowcount");
                    if (count==0){
                            JOptionPane.showMessageDialog(null,"<html>Data user masih kosong, gunakan:<br> "
                                    + "User Name = admin <br> password = admin <br>untuk LOGIN<html>",
                                    "Khansa POS",JOptionPane.INFORMATION_MESSAGE); 
                    }
        }
            catch(HeadlessException | SQLException b){
                JOptionPane.showMessageDialog(null, b.getMessage());
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uPanelRoundrect1 = new Utility.UPanelRoundrect();
        uPanelRoundrect2 = new Utility.UPanelRoundrect();
        jSeparator2 = new javax.swing.JSeparator();
        PasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new Utility.UButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSetting = new Utility.UButton();
        btnClose1 = new Utility.UButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Khansa POS");
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uPanelRoundrect1.setBackground(new java.awt.Color(153, 153, 153));
        uPanelRoundrect1.setKetebalanBorder(2.5F);
        uPanelRoundrect1.setWarnaBackground(new java.awt.Color(60, 93, 93));
        uPanelRoundrect1.setWarnaBorder(new java.awt.Color(187, 220, 220));
        uPanelRoundrect1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uPanelRoundrect2.setKetebalanBorder(2.5F);
        uPanelRoundrect2.setWarnaBorder(new java.awt.Color(187, 220, 220));
        uPanelRoundrect2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(230, 230, 230));
        uPanelRoundrect2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 300, -1));

        PasswordField.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        PasswordField.setToolTipText(null);
        PasswordField.setBorder(null);
        PasswordField.setOpaque(false);
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });
        uPanelRoundrect2.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 300, 20));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Password");
        jLabel2.setToolTipText(null);
        uPanelRoundrect2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, -1));

        jSeparator1.setForeground(new java.awt.Color(230, 230, 230));
        uPanelRoundrect2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, 10));

        txtUserName.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtUserName.setToolTipText(null);
        txtUserName.setBorder(null);
        txtUserName.setOpaque(false);
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });
        uPanelRoundrect2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 300, 20));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("User Name");
        jLabel1.setToolTipText(null);
        uPanelRoundrect2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        uPanelRoundrect2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, 10));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel5.setText("Welcome");
        jLabel5.setToolTipText(null);
        uPanelRoundrect2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 30));

        btnLogin.setText("Log In");
        btnLogin.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnLogin.setKetebalanBorder(2.0F);
        btnLogin.setKetumpulanSudut(35);
        btnLogin.setPreferredSize(new java.awt.Dimension(150, 38));
        btnLogin.setWarnaBackground(new java.awt.Color(0, 123, 255));
        btnLogin.setWarnaBackgroundHover(new java.awt.Color(77, 200, 255));
        btnLogin.setWarnaBackgroundPress(new java.awt.Color(0, 123, 255));
        btnLogin.setWarnaBorder(new java.awt.Color(77, 200, 255));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        uPanelRoundrect2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 270, -1));

        uPanelRoundrect1.add(uPanelRoundrect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 155, 340, 330));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\logoKhansaLogin.png")); // NOI18N
        jLabel3.setToolTipText(null);
        uPanelRoundrect1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 220, 70));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Point Of Sale");
        jLabel6.setToolTipText(null);
        uPanelRoundrect1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        btnSetting.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\iconSettings16.png")); // NOI18N
        btnSetting.setMnemonic('c');
        btnSetting.setText("Setting Database");
        btnSetting.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSetting.setPreferredSize(new java.awt.Dimension(70, 30));
        btnSetting.setWarnaBackground(new java.awt.Color(60, 93, 93));
        btnSetting.setWarnaBackgroundHover(new java.awt.Color(60, 93, 93));
        btnSetting.setWarnaBackgroundPress(new java.awt.Color(60, 93, 93));
        btnSetting.setWarnaBorder(new java.awt.Color(60, 93, 93));
        btnSetting.setWarnaForeground(new java.awt.Color(153, 153, 153));
        btnSetting.setWarnaForegroundHover(new java.awt.Color(255, 0, 0));
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        uPanelRoundrect1.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 170, -1));

        btnClose1.setMnemonic('c');
        btnClose1.setText("Close");
        btnClose1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnClose1.setPreferredSize(new java.awt.Dimension(70, 30));
        btnClose1.setWarnaBackground(new java.awt.Color(60, 93, 93));
        btnClose1.setWarnaBackgroundHover(new java.awt.Color(60, 93, 93));
        btnClose1.setWarnaBackgroundPress(new java.awt.Color(60, 93, 93));
        btnClose1.setWarnaBorder(new java.awt.Color(60, 93, 93));
        btnClose1.setWarnaForeground(new java.awt.Color(153, 153, 153));
        btnClose1.setWarnaForegroundHover(new java.awt.Color(255, 0, 0));
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        uPanelRoundrect1.add(btnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 5, -1, -1));

        getContentPane().add(uPanelRoundrect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 550));

        getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(371, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            PasswordField.setText(null);
            PasswordField.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
          txtUserName.setText("");
         }
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
           if(evt.getKeyCode() == KeyEvent.VK_ENTER){
               Login();
           } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
          PasswordField.setText("");
         }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        Keluar();
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        Settings();
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void Keluar(){
        //UIManager.put("OptionPane.noButtonText", "Tidak");
        //UIManager.put("OptionPane.yesButtonText", "Ya");
        //if (JOptionPane.showConfirmDialog(null, "Transaksi sudah disimpan, Apakah Anda Yakin Ingin Keluar?", "Khansa POS", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
       // }
    }
    private void Settings(){
          new KoneksiSetting().setVisible(true);
         dispose();  
    }
    
    private void Login() {
        final String secretKey = "khansaPOS";
     
        String userName= String.valueOf(txtUserName.getText());
        String password = String.valueOf(PasswordField.getPassword());
        String encryptedString = UAES.encrypt(password, secretKey) ;      
             
        if (txtUserName.getText() == null || txtUserName.getText().trim().isEmpty()||PasswordField.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "User Name atau Password Tidak Boleh Kosong!!", "Khansa POS", 
                    JOptionPane.WARNING_MESSAGE);
        }else {           
            if (count==0  && "admin".equals(password) && "admin".equals(userName)){             
                sessionId="0";
                sessionName="Login Pertama";
                sessionLevel="Admin";
                new Beranda().setVisible(true);               
                dispose();                        
            } else if (count > 0){
                try{                   
                    java.sql.Connection con =  new UDbConnection().koneksi();
                    java.sql.Statement st = con.createStatement();
                    java.sql.ResultSet rsLogin = st.executeQuery("SELECT * FROM users WHERE user_name='"+txtUserName.getText()
                                +"' AND user_password='"+encryptedString+"'");
        
                            if(rsLogin.next()){    
                                sessionId=rsLogin.getString("user_id");
                                sessionName=rsLogin.getString("user_name");
                                sessionLevel=rsLogin.getString("user_level");
                                new Beranda().setVisible(true);               
                                dispose(); 
                            } else{
                                JOptionPane.showMessageDialog(null,"Username Atau Password Salah!");
                                Bersih();
                            }
                } 
                    catch(HeadlessException | SQLException b){
                        JOptionPane.showMessageDialog(null, b.getMessage());
                    }
               
            } else {
                JOptionPane.showMessageDialog(null,"Gunakan User Name = admin, Password = admin");
                Bersih();
            }
        }
    }   

private void Bersih(){
    txtUserName.setText("");
    PasswordField.setText("");
    txtUserName.requestFocus();
}    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {  
            Frame f=new Login();                        
           // f.setIconImage(Toolkit.getDefaultToolkit().getImage("image\\keys.png"));             
            f.setVisible(true);
        });
    }



 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private Utility.UButton btnClose1;
    private Utility.UButton btnLogin;
    private Utility.UButton btnSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtUserName;
    private Utility.UPanelRoundrect uPanelRoundrect1;
    private Utility.UPanelRoundrect uPanelRoundrect2;
    // End of variables declaration//GEN-END:variables

   

    
}
