package khansapos;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;


public class Beranda extends javax.swing.JFrame {


    public Beranda() {
        initComponents();
        Icon();
        setUser();   
        setWaktu();
        setJam();    
    }


    private void Icon(){       
        ImageIcon icon = new ImageIcon("image/khansa.png");
        setIconImage(icon.getImage());
        
    }
    
    private void setUser(){      
            String userId = Utility_Session.getUserId();
            String userName=Utility_Session.getUserName();
            String userLevel=Utility_Session.getUserLevel();          
            
            //lblId.setText(userId);
            lblUser.setText(userLevel + ":  " +userName);
            //lblLevel.setText(userLevel);       
    }
       
   private void setWaktu() {
             java.util.Date tglsekarang = new java.util.Date();
            SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
            String tanggal = smpdtfmt.format(tglsekarang);
            SimpleDateFormat fTahun = new SimpleDateFormat(" yyyy", Locale.getDefault());
            String tahun="(c)" + fTahun.format(tglsekarang) + "  R. Cahyono";
             lblTanggal.setText(tanggal);
             lblCopyright.setText(tahun);
    }
  
    private void setJam(){
            ActionListener taskPerformer = (ActionEvent evt) -> {            
            String nol_jam = "", nol_menit = "";
            Calendar calendar = Calendar.getInstance();            
            int nilai_jam = calendar.get(Calendar.HOUR_OF_DAY);
            int nilai_menit = calendar.get(Calendar.MINUTE);
            // int nilai_detik = calendar.get(Calendar.SECOND);
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            // if(nilai_detik <= 9) nol_detik= "0";
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            //String detik = nol_detik + Integer.toString(nilai_detik);
            lblJam.setText(jam+":"+menit);
            // lblJam.setText(jam+":"+menit+":"+detik+"");
        };
    new Timer(1000, taskPerformer).start();
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        Penjualan = new javax.swing.JMenuItem();
        pjBayar = new javax.swing.JMenuItem();
        pjRetur = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Pembelian = new javax.swing.JMenuItem();
        pbBayar = new javax.swing.JMenuItem();
        pbRetur = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        lapPembelian = new javax.swing.JMenuItem();
        lapPenjualan = new javax.swing.JMenuItem();
        lapLaba = new javax.swing.JMenuItem();
        lapGrafik = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mBarang = new javax.swing.JMenuItem();
        mSuplier = new javax.swing.JMenuItem();
        mMember = new javax.swing.JMenuItem();
        mUser = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        logOut = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        panelSidebar = new javax.swing.JPanel();
        btnSc1 = new javax.swing.JLabel();
        btnSc2 = new javax.swing.JLabel();
        btnSc3 = new javax.swing.JLabel();
        btnSc4 = new javax.swing.JLabel();
        btnSc5 = new javax.swing.JLabel();
        btnSc6 = new javax.swing.JLabel();
        btnSc7 = new javax.swing.JLabel();
        btnSc8 = new javax.swing.JLabel();
        btnSc9 = new javax.swing.JLabel();
        lblCopyright = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        btnMenu = new javax.swing.JLabel();
        panelUtama =  new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(new Color(244,244,244));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jPanel1 = new javax.swing.JPanel();

        popUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Penjualan.setBackground(new java.awt.Color(0, 0, 0));
        Penjualan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penjualan.setText("Penjualan");
        popUp.add(Penjualan);

        pjBayar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pjBayar.setText("Penjualan Bayar");
        popUp.add(pjBayar);

        pjRetur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pjRetur.setText("Penjualan Retur");
        popUp.add(pjRetur);
        popUp.add(jSeparator1);

        Pembelian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pembelian.setText("Pembelian");
        popUp.add(Pembelian);

        pbBayar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pbBayar.setText("Pembelian Bayar");
        popUp.add(pbBayar);

        pbRetur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pbRetur.setText("Pembelian Retur");
        popUp.add(pbRetur);
        popUp.add(jSeparator2);

        lapPembelian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lapPembelian.setText("Laporan Pembelian");
        popUp.add(lapPembelian);

        lapPenjualan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lapPenjualan.setText("Laporan Penjualan");
        popUp.add(lapPenjualan);

        lapLaba.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lapLaba.setText("Laporan Laba");
        popUp.add(lapLaba);

        lapGrafik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lapGrafik.setText("Laporan Grafik");
        popUp.add(lapGrafik);
        popUp.add(jSeparator3);

        mBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mBarang.setText("Master Barang");
        popUp.add(mBarang);

        mSuplier.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mSuplier.setText("Master Suplier");
        mSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSuplierActionPerformed(evt);
            }
        });
        popUp.add(mSuplier);

        mMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMember.setText("Master Member");
        mMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMemberActionPerformed(evt);
            }
        });
        popUp.add(mMember);

        mUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mUser.setText("Master User");
        mUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUserActionPerformed(evt);
            }
        });
        popUp.add(mUser);
        popUp.add(jSeparator4);

        logOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        popUp.add(logOut);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 248, 248));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 764));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\logoKhansa1.png")); // NOI18N
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 50));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        panelSidebar.setBackground(new java.awt.Color(0, 123, 255));
        panelSidebar.setPreferredSize(new java.awt.Dimension(120, 714));

        btnSc1.setBackground(new java.awt.Color(0, 123, 255));
        btnSc1.setDisplayedMnemonic('1');
        btnSc1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc1.setForeground(new java.awt.Color(255, 255, 255));
        btnSc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc1.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\025-shopping cart.png")); // NOI18N
        btnSc1.setLabelFor(this);
        btnSc1.setToolTipText(null);
        btnSc1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc1.setFocusTraversalPolicyProvider(true);
        btnSc1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc1.setOpaque(true);
        btnSc1.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc1FocusLost(evt);
            }
        });
        btnSc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc1MousePressed(evt);
            }
        });

        btnSc2.setBackground(new java.awt.Color(0, 123, 255));
        btnSc2.setDisplayedMnemonic('2');
        btnSc2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc2.setForeground(new java.awt.Color(102, 102, 102));
        btnSc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc2.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\027-money-bag.png")); // NOI18N
        btnSc2.setLabelFor(this);
        btnSc2.setToolTipText(null);
        btnSc2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc2.setFocusTraversalPolicyProvider(true);
        btnSc2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc2.setOpaque(true);
        btnSc2.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc2FocusLost(evt);
            }
        });
        btnSc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc2MousePressed(evt);
            }
        });

        btnSc3.setBackground(new java.awt.Color(0, 123, 255));
        btnSc3.setDisplayedMnemonic('3');
        btnSc3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc3.setForeground(new java.awt.Color(102, 102, 102));
        btnSc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc3.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\003-buy.png")); // NOI18N
        btnSc3.setLabelFor(this);
        btnSc3.setToolTipText(null);
        btnSc3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc3.setFocusTraversalPolicyProvider(true);
        btnSc3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc3.setOpaque(true);
        btnSc3.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc3FocusLost(evt);
            }
        });
        btnSc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc3MousePressed(evt);
            }
        });

        btnSc4.setBackground(new java.awt.Color(0, 123, 255));
        btnSc4.setDisplayedMnemonic('4');
        btnSc4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc4.setForeground(new java.awt.Color(102, 102, 102));
        btnSc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc4.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\009-time-is-money.png")); // NOI18N
        btnSc4.setLabelFor(this);
        btnSc4.setToolTipText(null);
        btnSc4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc4.setFocusTraversalPolicyProvider(true);
        btnSc4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc4.setOpaque(true);
        btnSc4.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc4FocusLost(evt);
            }
        });
        btnSc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc4MousePressed(evt);
            }
        });

        btnSc5.setBackground(new java.awt.Color(0, 123, 255));
        btnSc5.setDisplayedMnemonic('5');
        btnSc5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc5.setForeground(new java.awt.Color(102, 102, 102));
        btnSc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc5.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\018-consultant.png")); // NOI18N
        btnSc5.setLabelFor(this);
        btnSc5.setToolTipText(null);
        btnSc5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc5.setFocusTraversalPolicyProvider(true);
        btnSc5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc5.setOpaque(true);
        btnSc5.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc5FocusLost(evt);
            }
        });
        btnSc5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc5MousePressed(evt);
            }
        });

        btnSc6.setBackground(new java.awt.Color(0, 123, 255));
        btnSc6.setDisplayedMnemonic('6');
        btnSc6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc6.setForeground(new java.awt.Color(102, 102, 102));
        btnSc6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc6.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\007-report.png")); // NOI18N
        btnSc6.setLabelFor(this);
        btnSc6.setToolTipText(null);
        btnSc6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc6.setFocusTraversalPolicyProvider(true);
        btnSc6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc6.setOpaque(true);
        btnSc6.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc6FocusLost(evt);
            }
        });
        btnSc6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc6MousePressed(evt);
            }
        });

        btnSc7.setBackground(new java.awt.Color(0, 123, 255));
        btnSc7.setDisplayedMnemonic('7');
        btnSc7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc7.setForeground(new java.awt.Color(102, 102, 102));
        btnSc7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc7.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\011-graph.png")); // NOI18N
        btnSc7.setLabelFor(this);
        btnSc7.setToolTipText(null);
        btnSc7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc7.setFocusTraversalPolicyProvider(true);
        btnSc7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc7.setOpaque(true);
        btnSc7.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc7FocusLost(evt);
            }
        });
        btnSc7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc7MousePressed(evt);
            }
        });

        btnSc8.setBackground(new java.awt.Color(0, 123, 255));
        btnSc8.setDisplayedMnemonic('8');
        btnSc8.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc8.setForeground(new java.awt.Color(102, 102, 102));
        btnSc8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc8.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\021-growth-2.png")); // NOI18N
        btnSc8.setLabelFor(this);
        btnSc8.setToolTipText(null);
        btnSc8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc8.setFocusTraversalPolicyProvider(true);
        btnSc8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc8.setOpaque(true);
        btnSc8.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc8FocusLost(evt);
            }
        });
        btnSc8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc8MousePressed(evt);
            }
        });

        btnSc9.setBackground(new java.awt.Color(0, 123, 255));
        btnSc9.setDisplayedMnemonic('9');
        btnSc9.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnSc9.setForeground(new java.awt.Color(102, 102, 102));
        btnSc9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSc9.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\icon48\\022-guarantee.png")); // NOI18N
        btnSc9.setLabelFor(this);
        btnSc9.setToolTipText(null);
        btnSc9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSc9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSc9.setFocusTraversalPolicyProvider(true);
        btnSc9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSc9.setOpaque(true);
        btnSc9.setPreferredSize(new java.awt.Dimension(102, 60));
        btnSc9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSc9FocusLost(evt);
            }
        });
        btnSc9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSc9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSc9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSc9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSc9MousePressed(evt);
            }
        });

        lblCopyright.setBackground(new java.awt.Color(255, 255, 255));
        lblCopyright.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
        lblCopyright.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText("(c) 2021  ERCE");

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addComponent(lblCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSc4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSc6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSc8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSc5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSc9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnSc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lblCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 120, -1));

        panelHeader.setBackground(new java.awt.Color(0, 0, 0));
        panelHeader.setPreferredSize(new java.awt.Dimension(1366, 50));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTanggal.setBackground(new java.awt.Color(85, 118, 118));
        lblTanggal.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTanggal.setText("23 September 2021");
        lblTanggal.setOpaque(true);
        panelHeader.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 0, 198, 50));

        btnExit.setBackground(new java.awt.Color(34, 67, 67));
        btnExit.setDisplayedMnemonic('x');
        btnExit.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setLabelFor(this);
        btnExit.setText("Exit");
        btnExit.setToolTipText(null);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setOpaque(true);
        btnExit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnExitFocusLost(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        panelHeader.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 58, 50));

        lblUser.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("Kasir: Cahyono");
        panelHeader.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 0, 214, 50));

        lblJam.setBackground(new java.awt.Color(85, 118, 118));
        lblJam.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblJam.setForeground(new java.awt.Color(204, 204, 0));
        lblJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJam.setText("12:34");
        lblJam.setOpaque(true);
        panelHeader.add(lblJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1243, 0, 67, 50));

        btnMenu.setBackground(new java.awt.Color(34, 67, 67));
        btnMenu.setDisplayedMnemonic('m');
        btnMenu.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenu.setIcon(new javax.swing.ImageIcon("D:\\Java\\Belajar Java\\KhansaPOS\\image\\MenuIcon32.png")); // NOI18N
        btnMenu.setLabelFor(this);
        btnMenu.setToolTipText(null);
        btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusTraversalPolicyProvider(true);
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.setOpaque(true);
        btnMenu.setPreferredSize(new java.awt.Dimension(75, 25));
        btnMenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnMenuFocusLost(evt);
            }
        });
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
        });
        panelHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 50, 50));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelUtama.setBackground(new java.awt.Color(242, 248, 248));
        panelUtama.setPreferredSize(new java.awt.Dimension(1246, 714));

        jPanel1.setBackground(new java.awt.Color(248, 251, 251));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1246, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );

        panelUtama.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        setBounds(0, 0, 1367, 764);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnExitFocusLost
        Keluar();
    }//GEN-LAST:event_btnExitFocusLost

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        Keluar();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new Color(255,255,255));
        btnExit.setBackground(new Color(217,0,0));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new Color(255,0,0));
        btnExit.setBackground(new Color(34,67,67));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMenuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnMenuFocusLost
        popUp.show(this,155, 55);     
    }//GEN-LAST:event_btnMenuFocusLost

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        btnMenu.setBackground(new Color(235,154,35));        
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        btnMenu.setBackground(new Color(34,67,67));        
    }//GEN-LAST:event_btnMenuMouseExited
   
    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {                                     
        popUp.show(this, 155, 55);
    }  
    
    private void btnSc1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc1FocusLost
        
    }//GEN-LAST:event_btnSc1FocusLost

    private void btnSc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc1MouseClicked
       
    }//GEN-LAST:event_btnSc1MouseClicked

    private void btnSc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc1MouseEntered
        btnSc1.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc1MouseEntered

    private void btnSc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc1MouseExited
        btnSc1.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc1MouseExited

    private void btnSc1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc1MousePressed

    private void btnSc2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc2FocusLost
       
    }//GEN-LAST:event_btnSc2FocusLost

    private void btnSc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc2MouseClicked
       
    }//GEN-LAST:event_btnSc2MouseClicked

    private void btnSc2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc2MouseEntered
        btnSc2.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc2MouseEntered

    private void btnSc2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc2MouseExited
        btnSc2.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc2MouseExited

    private void btnSc2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc2MousePressed

    private void btnSc3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc3FocusLost
       
    }//GEN-LAST:event_btnSc3FocusLost

    private void btnSc3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc3MouseClicked
       
    }//GEN-LAST:event_btnSc3MouseClicked

    private void btnSc3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc3MouseEntered
        btnSc3.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc3MouseEntered

    private void btnSc3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc3MouseExited
        btnSc3.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc3MouseExited

    private void btnSc3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc3MousePressed

    private void btnSc4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc4FocusLost
        
    }//GEN-LAST:event_btnSc4FocusLost

    private void btnSc4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc4MouseClicked
        
    }//GEN-LAST:event_btnSc4MouseClicked

    private void btnSc4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc4MouseEntered
        btnSc4.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc4MouseEntered

    private void btnSc4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc4MouseExited
        btnSc4.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc4MouseExited

    private void btnSc4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc4MousePressed

    private void btnSc5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc5FocusLost
       
    }//GEN-LAST:event_btnSc5FocusLost

    private void btnSc5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc5MouseClicked
       
    }//GEN-LAST:event_btnSc5MouseClicked

    private void btnSc5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc5MouseEntered
        btnSc5.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc5MouseEntered

    private void btnSc5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc5MouseExited
       btnSc5.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc5MouseExited

    private void btnSc5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc5MousePressed

    private void btnSc6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc6FocusLost
        
    }//GEN-LAST:event_btnSc6FocusLost

    private void btnSc6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc6MouseClicked
        
    }//GEN-LAST:event_btnSc6MouseClicked

    private void btnSc6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc6MouseEntered
        btnSc6.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc6MouseEntered

    private void btnSc6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc6MouseExited
        btnSc6.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc6MouseExited

    private void btnSc6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc6MousePressed

    private void btnSc7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc7FocusLost
       
    }//GEN-LAST:event_btnSc7FocusLost

    private void btnSc7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc7MouseClicked
       
    }//GEN-LAST:event_btnSc7MouseClicked

    private void btnSc7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc7MouseEntered
        btnSc7.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc7MouseEntered

    private void btnSc7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc7MouseExited
        btnSc7.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc7MouseExited

    private void btnSc7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc7MousePressed

    private void btnSc8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc8FocusLost
       
    }//GEN-LAST:event_btnSc8FocusLost

    private void btnSc8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc8MouseClicked
        
    }//GEN-LAST:event_btnSc8MouseClicked

    private void btnSc8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc8MouseEntered
        btnSc8.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc8MouseEntered

    private void btnSc8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc8MouseExited
        btnSc8.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc8MouseExited

    private void btnSc8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc8MousePressed

    private void btnSc9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSc9FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc9FocusLost

    private void btnSc9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc9MouseClicked
        Logout();
    }//GEN-LAST:event_btnSc9MouseClicked

    private void btnSc9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc9MouseEntered
        btnSc9.setBackground(new Color(235,154,35));
    }//GEN-LAST:event_btnSc9MouseEntered

    private void btnSc9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc9MouseExited
        btnSc9.setBackground(new Color(0,123,255));
    }//GEN-LAST:event_btnSc9MouseExited

    private void btnSc9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSc9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSc9MousePressed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        Logout();
    }//GEN-LAST:event_logOutActionPerformed

    private void mUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUserActionPerformed
        UserFormShow();
    }//GEN-LAST:event_mUserActionPerformed

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        popUp.show(this, 155, 55);  
    }//GEN-LAST:event_btnMenuMousePressed

    private void mMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMemberActionPerformed
        MemberFormShow();
    }//GEN-LAST:event_mMemberActionPerformed

    private void mSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSuplierActionPerformed
        SuplierFormShow();
    }//GEN-LAST:event_mSuplierActionPerformed
  
      
    private void UserFormShow(){
        UserForm Uf= new UserForm();
        panelUtama.add(Uf);
        Uf.setVisible(true);           
    }
    
    private void MemberFormShow(){
        MemberForm Mf = new MemberForm();
        panelUtama.add(Mf);
        Mf.setVisible(true);
    }
    
    private void SuplierFormShow(){
        SuplierForm Sf = new SuplierForm();
        panelUtama.add(Sf);
        Sf.setVisible(true);
    }
        
    private void popUpMenu(){
           
    }
    
    private void HideAll(){

        UserFormAdd ufa = new UserFormAdd();
        this.getParent().add(ufa);
        ufa.setVisible(true);
        this.setVisible(false);
           
    }
    private void Logout(){
          new LoginForm().setVisible(true);
         dispose();  
    }
    private void Keluar(){
        System.exit(0);
    }
    
    
    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            
            new Beranda().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Pembelian;
    private javax.swing.JMenuItem Penjualan;
    private static javax.swing.JLabel btnExit;
    private static javax.swing.JLabel btnMenu;
    private static javax.swing.JLabel btnSc1;
    private static javax.swing.JLabel btnSc2;
    private static javax.swing.JLabel btnSc3;
    private static javax.swing.JLabel btnSc4;
    private static javax.swing.JLabel btnSc5;
    private static javax.swing.JLabel btnSc6;
    private static javax.swing.JLabel btnSc7;
    private static javax.swing.JLabel btnSc8;
    private static javax.swing.JLabel btnSc9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem lapGrafik;
    private javax.swing.JMenuItem lapLaba;
    private javax.swing.JMenuItem lapPembelian;
    private javax.swing.JMenuItem lapPenjualan;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem mBarang;
    private javax.swing.JMenuItem mMember;
    private javax.swing.JMenuItem mSuplier;
    private javax.swing.JMenuItem mUser;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JDesktopPane panelUtama;
    private javax.swing.JMenuItem pbBayar;
    private javax.swing.JMenuItem pbRetur;
    private javax.swing.JMenuItem pjBayar;
    private javax.swing.JMenuItem pjRetur;
    private javax.swing.JPopupMenu popUp;
    // End of variables declaration//GEN-END:variables
}
